### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by Dwyte** [Leo4815162342/dukascopy-tools#12]
`dukascopy-cli -i eurusd -from 2016-08-07 -to 2017-08-07 -t tick -f csv`

I tried downloading a year worth of data, '16-'17 and it gave an error `Invalid string length` after the 100% bar.

**Comment by Leo4815162342** [comment]
Thanks for raising the issue. Seems I can reproduce it as well.

I think we'll need to update the strategy for downloading the `tick` data. Since we're downloading quite a lot files.
For example downloading a year of tick data means we'd need to fetch 24 (each hour of tick data is served in a separate file) multiplied by 365, which is 8760 files, some of those can be corrupted for some reason.
I'll try to work on a solution in which we'd be able to fetch these files properly.
